### PR TITLE
Add a helper to split a SegmentCollection on a given segment

### PR DESCRIPTION
**Pull request by JocelynDelalande**

### CODE REVIEW

**Comment by nerdoc** [comment]
Col, could you add a docstring?

**Comment by nerdoc** [comment]
(and a test would be extremely great...)

**Comment by JocelynDelalande** [comment]
You are totally right, this is done :) (and added changelog entry)

If this PR suits you, could we release 0.1 with it included ?

**Comment by nerdoc** [comment]
> You are totally right, this is done :) (and added changelog entry)
> 
> If this PR suits you, could we release 0.1 with it included ?

Sure, sounds great. Give me a few days pls, gotta wrap my had around many things ATM.

**Comment by nerdoc** [comment]
Thanks, great addon

**Comment by nerdoc** [comment]
0.1.0 released!

**Comment by JocelynDelalande** [comment]
It is nice to work with you :).

**Comment by nerdoc** [comment]
Oh, *you* are doing most of the work ATM... The pleasure is in my side! Thanks for that great code so far!

**Comment by nerdoc** [comment]
I never thought that, besides me sometimes, anyone will find pydifact useful...

**Pull request merged**
