### PR TITLE
Added test for edifact message UNA and UNB

### PR DESCRIPTION
**Pull request by maanas**
Added test for edifact message UNA and UNB for PAXLST message

### CODE REVIEW

**Comment by nerdoc** [comment]
Hm, what are you testing exactly here? Aren't you testing the parser? (by creating a segment and checking if the array was created correctly in the SegmentsCollection?

ATM a message like PAXLST is not implemented and will be implemented most probably by a class like `PaxlstMessage` with tests for it.
Which does not mean I don't want to accept this PR...

* Could you maybe move that test into `tests/messagetypes/paxlst`
* New tests preferrably should be pytest, not Django unittests. ok for you?

**Comment by maanas** [comment]
Yes, I am trying to implement PAXLST PNRGOV message. We are doing a port of 
https://github.com/US-CBP/GTAS in pure python / django 
https://github.com/minelytics/GTAS

2. I will move the test to the location you said and move to pytest as well. 

3. If you can guide we would like to add the PR for parsers https://github.com/minelytics/GTAS/tree/branch_1f_parsers/gtas/parsers/paxlst to pydifact.  We are writing a lot of parser for EDIFact PAXLST and PNR gov. We also intend to write validators. if I can move all the functions to pydifact that would be great. Then I can just use the wrapper classes to put the code.

4. I will send a new PR request shortly.

**Comment by maanas** [comment]
Updated the code.
a) Moved the test to messagetype
b) Use pytest in place of unittest

I noticed in some test there are still code using the unittest, shall i convert that to pytest?

**Comment by nerdoc** [comment]
Thanks, seems good!
Just one thing: pydifact uses [black](https://pypi.org/project/black/) to format all code. I did that already in another commit.

**Comment by nerdoc** [comment]
Oh, and yes, if you really want to do the work and make the full transit to pytest for the others, feel free - but that's really low priority. I'd  just like to have new tests in pytest.

**Pull request merged**
